# categories for documents
DOCUMENT_CATEGORIES = ["culture"]

EXT_TO_TYPE = {
    ".txt": "text-document",
    ".md": "text-document",
    ".pdf": "text-document",
    ".cob": "code",
    ".cpy": "code",
    ".java": "code",
    ".py": "code",
    ".js": "code",
    ".jsx": "code",
    ".ts": "code",
    ".tsx": "code",
    ".go": "code",
    ".rb": "code",
    ".php": "code",
    ".cs": "code",
    ".cpp": "code",
    ".h": "code",
    ".css": "code",
    ".scss": "code",
    ".sass": "code",
    ".html": "code",
    ".xml": "code",
    ".yaml": "code",
    ".yml": "code",
    ".sql": "code",
    # ".csv": "slack",
    # ".json": "slack",
    ".gitlog": "git",
    ".log": "git",
}
